Capstone project-Mobile desktop version
binodbhusal/Capstone-project-Conference-page pull request #1
Opened 2023-04-21 13:49 UTC by binodbhusal

**The following activities were carried out:**
- Created HTML CSS and Javascript files
-  have versions for 2 different screen sizes:
         _Mobile: up to 768px wide.
         Desktop: 768px or wider._
- Interactions:
      _The home page has a link to the About page in the menu.
      The logo in the header links to the home page_
- The mobile menu appears over the page when the user clicks (or taps) the hamburger button on the header.
- The mobile menu has a close (X) button that closes the menu.
- The section "Featured speakers" was created dynamically in JavaScript.
                                                    
 **Thank you !!**

2023-04-21 15:57 UTC, alexander16108 requested changes
Hi @binodbhusal , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/4IwnscWi8r5NRuLGRW/giphy.gif"/>

## Highlights

- [ ]  All linters are passing ✔️
- [ ]  Good commit history ✔️
- [ ]  Good PR description ✔️
- [ ]  Follow Gitflow ✔️

## Required Changes ♻️
_Check the comments under the review._

- [ ] You should record a video presenting the features of the project.
- [ ] The maximum length of the video is 5 minutes.
- [ ] The video should contain a clear and objective description of the project in professional English. - [ ] The topic and purpose of the project should be made clear.
- [ ] The video should contain a demo of the project, showing the pages in different screen sizes.
- [ ] The video should contain a highlight about a piece of the code the student finds interesting or is proud of making.
- [ ]  Please consider adding a readme file using this template from Microverse [Click Here >>](https://github.com/microverseinc/readme-template), remember to customize the contents of the readme file to your project.
- [ ] You should make use of GitHub Pages to deploy the web pages.
- [ ]  The project should be deployed properly, and all pages, links, and images work as expected.
- [ ]  A link to the deployed project should be present in the README.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-21 15:57 UTC, alexander16108 commented on index.html
> +</nav>
as seen required your design should be similar to the original template design but as we can see below your nav bar need to add padding in between the padding of each link to create a similar mock-up of the template seen below also update the colour and font size of each item 

your design
![image](https://user-images.githubusercontent.com/60612329/233664398-dd6df5c2-11fc-4e8a-9861-2ff7f74a3ee8.png)

template
![image](https://user-images.githubusercontent.com/60612329/233664531-67f1dd21-1694-45e9-8387-7de3b9968852.png)

2023-04-21 15:57 UTC, alexander16108 commented on index.html
> +            </section>
As seen required your design should be similar to the original template design but as we can see below your headline section is not properly done, perform the following actions.

- [ ] Please remove the transition on the timestamp it disrupts the flow of the rest of the webpage.
- [ ] Update the background image of the desktop version of your headline to match your template.
- [ ] Please update your font colour and use the required fonts which are `lato` and `cocogoose`.
- [ ] Please update the space of your webpage to match the original design

template design 

![image](https://user-images.githubusercontent.com/60612329/233668150-4d53523c-bc0d-4d07-b3b4-0f439a71a5ad.png)

your design 
![image](https://user-images.githubusercontent.com/60612329/233668526-c068684a-9ab5-4a64-8d1a-6d10d3efb11c.png)

2023-04-21 15:57 UTC, alexander16108 commented on index.html
> +          </section>
you've done a good job recreating the section of the main program but you still need to do the following to improve your design 😄 

- [ ] There should be some visible padding in between each card.
- [ ] The width of the cards should be smaller with the font size and font weight of each header should be thicker and larger
- [ ] There should be more padding within and outside the cards to make your program section look less cramped and untidy 😄 

your design
![image](https://user-images.githubusercontent.com/60612329/233672315-a20f158c-bb30-4b8b-84bd-218c70a50182.png)

template design
![image](https://user-images.githubusercontent.com/60612329/233672763-9e7cf9a2-cd26-4178-bc68-e06331624184.png)

2023-04-21 15:57 UTC, alexander16108 commented on index.html
> +          </section>
you've done a good job recreating the section of the feature speakers but you still need to do the following to improve your design 😄

- [ ] Please follow the design as seen in the template below
- [ ] Please add the black and white checkers background to each image and increase the size of the image to match the template
- [ ] Please reduce the font size and the width of each piece of information by the speakers

your design
![image](https://user-images.githubusercontent.com/60612329/233675402-642030a6-e542-44ed-b931-735ca5a568b0.png)


template design
![image](https://user-images.githubusercontent.com/60612329/233675497-ae3831c4-c1eb-42d8-b90f-3e74383eaf49.png)

2023-04-21 15:57 UTC, alexander16108 commented on about.html
> +</nav>
as seen required your design should be similar to the original template design but as we can see below your nav bar need to add padding in between the padding of each link to create a similar mock-up of the template seen below also update the colour and font size of each item 

your design
![image](https://user-images.githubusercontent.com/60612329/233664398-dd6df5c2-11fc-4e8a-9861-2ff7f74a3ee8.png)

template
![image](https://user-images.githubusercontent.com/60612329/233664531-67f1dd21-1694-45e9-8387-7de3b9968852.png)

2023-04-21 15:57 UTC, alexander16108 commented on about.html
> +            </section>
As seen required your design should be similar to the original template design but as we can see below your headline section is not properly done, perform the following actions.

- [ ] Update the background image of the desktop version of your headline to match your template.
- [ ] Please update your font colour and use the required fonts which are `lato` and `cocogoose`.
- [ ] Please update the space of your webpage to match the original design

template design 
![image](https://user-images.githubusercontent.com/60612329/233676751-71227c2f-9dc0-4062-8943-1b3d6e0fb4fc.png)


your design
![image](https://user-images.githubusercontent.com/60612329/233676584-a51aca5a-0715-4b0b-af6c-20f9eb2028a7.png)

2023-04-21 15:57 UTC, alexander16108 commented on about.html
> +            </section>
your design should match the template design as seen below
your design
![image](https://user-images.githubusercontent.com/60612329/233677301-2c2d1efb-c98c-450e-9beb-25441ae31a79.png)

template design
![image](https://user-images.githubusercontent.com/60612329/233677469-7e60b062-7904-4018-9065-07cb542bfd55.png)

2023-04-21 15:57 UTC, alexander16108 commented on index.html
> +          </section>
in the mobile version of your  main program design your should preform the following corrections

- [ ] your cards should have their elements organized in a horizontal row, with the image at the left, the title in the centre, and the description at the right.
- [ ] see the whole program should not be visible

template
![image](https://user-images.githubusercontent.com/60612329/233678603-6b0497fa-b2f3-4620-b85e-7f024f41d066.png)

your design
![image](https://user-images.githubusercontent.com/60612329/233678747-be5406b1-67c1-4b28-a0a0-07557fb2ec3d.png)

2023-04-21 15:57 UTC, alexander16108 commented on about.html
> +            </section>
your design should match the template design as seen below
your design 😄 

please eliminate spacing on the sides 
as seen with the desktop version you should add the red background on the cards and align the texts to the center
![image](https://user-images.githubusercontent.com/60612329/233679835-f9a8a632-21dc-46d8-862e-6e1bfb93fea7.png)

![image](https://user-images.githubusercontent.com/60612329/233680021-5c346579-ee37-424c-9314-d51d2e24934a.png)

![image](https://user-images.githubusercontent.com/60612329/233680150-54c64126-4194-49ea-92fa-86b770f2108a.png)

template design
![image](https://user-images.githubusercontent.com/60612329/233680337-ceedc1c3-6c4b-4b24-8eb8-881d90bc87c1.png)

![image](https://user-images.githubusercontent.com/60612329/233680468-3e474619-687d-40ba-a8d5-8473f6582915.png)

2023-04-21 15:57 UTC, alexander16108 commented on style.css
> +    gap: 10px;
your css design should be a mobile-first design and currently its not 😄

2023-04-22 12:42 UTC, Trast00 requested changes
# Change Required ♻️ 
Hi @binodbhusal , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![almost-there-reach](https://user-images.githubusercontent.com/74411135/225062441-793da0f4-3ef1-4d98-bee9-9c200c7121a7.gif)

## Highlights
- Project look awesome 🍏 🌷 
- Code is clean and well organized 🧼 💯 
- Great design 😮 

 ## Required Changes ♻️
_Check the comments under the review._

- Please consider implementing all the change I left below (inline comment).
**(Here is the  [Provided design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015) mentioned in the inline comment)**

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@Trast00) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-22 12:42 UTC, Trast00 commented on style.css
> +}
- [ ] Kindly, as requested by the previous reviewer, make sure all sections take the full width of the screen:

**Your project**
![image](https://user-images.githubusercontent.com/74411135/233784695-f1d1e667-3034-4ffb-a83d-f6ea9e83613c.png)

**Your project**
![image](https://user-images.githubusercontent.com/74411135/233784740-41f4c42e-d04c-4cd3-9204-bb04dc866dcb.png)

this happens because of the `margin: auto 0 author 280px`, consider using `width: 100%;` and `justify-content: space-between;`. This will make your project responsive for most of screen size.

- [ ] **[OPTIONAL]** Kindly, consider using responsive units like `%` for witdh. I notice that there is many static widths (eg: for logo and submit images), which can make some element overflow horizontally or (in your case) some element seem to not take the full width. When possible consider using `width: ...%` instead of `width: ...px`. 

This will make your project way prettier which will improve the user experience 📱  😄 👍

2023-04-22 13:53 UTC, Felix45 approved these changes
# Approved :green_circle:  🎉  🎉  🎉  🎉  🎉 
Hi @binodbhusal , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://camo.githubusercontent.com/5f6b955314ad7a8c010bb5de56877a2fa40a6d2bc5aeabd629e6a150f73afd97/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f744965434c6b423867655974572f67697068792e676966" width="375px" />

## Highlights :heavy_check_mark: 
- [x] Good UI design :white_check_mark: 
- [x] Website is responsive on different devices :white_check_mark: 
- [x] GitHub flow is used correctly :white_check_mark:  
- [x]  Pull request has a descriptive title and summary :white_check_mark: 

## Optional suggestions
- [Optional] Good job on this capstone project it's very nice. I noticed that your repository doesn't have a professional readme file :cry: this means someone going through your repository won't even know where the live demo is deployed online. Please consider adding a readme file using this template from Microverse [Click Here >>](https://github.com/microverseinc/readme-template), remember to customize the contents of the readme file to your project. I highly recommend this change, since it should have been mentioned as a required change by the first reviewer.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 11:03 UTC, merged